//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerManagerEntities : DbContext
    {
        public CustomerManagerEntities()
            : base("name=CustomerManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_AttendType> Table_AttendType { get; set; }
        public virtual DbSet<Table_Cluster> Table_Cluster { get; set; }
        public virtual DbSet<Table_Consumables> Table_Consumables { get; set; }
        public virtual DbSet<Table_Contactdetails> Table_Contactdetails { get; set; }
        public virtual DbSet<Table_Country> Table_Country { get; set; }
        public virtual DbSet<Table_CustomerRegistartion> Table_CustomerRegistartion { get; set; }
        public virtual DbSet<Table_Faults> Table_Faults { get; set; }
        public virtual DbSet<Table_Features> Table_Features { get; set; }
        public virtual DbSet<Table_FollowUpDetails> Table_FollowUpDetails { get; set; }
        public virtual DbSet<Table_InteractionsData> Table_InteractionsData { get; set; }
        public virtual DbSet<Table_InvoiceDocuments> Table_InvoiceDocuments { get; set; }
        public virtual DbSet<Table_InvoicePerticular> Table_InvoicePerticular { get; set; }
        public virtual DbSet<Table_LocationDetails> Table_LocationDetails { get; set; }
        public virtual DbSet<Table_MachineCustomerRequestsDetails> Table_MachineCustomerRequestsDetails { get; set; }
        public virtual DbSet<Table_MachineCustomerSansSDetails> Table_MachineCustomerSansSDetails { get; set; }
        public virtual DbSet<Table_MachineFeatureDetails> Table_MachineFeatureDetails { get; set; }
        public virtual DbSet<Table_MachineRegistration> Table_MachineRegistration { get; set; }
        public virtual DbSet<Table_Model> Table_Model { get; set; }
        public virtual DbSet<Table_Priority> Table_Priority { get; set; }
        public virtual DbSet<Table_Region> Table_Region { get; set; }
        public virtual DbSet<Table_Requests> Table_Requests { get; set; }
        public virtual DbSet<Table_RequestsFormData> Table_RequestsFormData { get; set; }
        public virtual DbSet<Table_RoleMaster> Table_RoleMaster { get; set; }
        public virtual DbSet<Table_Route> Table_Route { get; set; }
        public virtual DbSet<Table_Sands> Table_Sands { get; set; }
        public virtual DbSet<Table_TravelBudget> Table_TravelBudget { get; set; }
        public virtual DbSet<Table_UserRegistration> Table_UserRegistration { get; set; }
        public virtual DbSet<Table_Zone> Table_Zone { get; set; }
    }
}
