//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TravelBudget
    {
        public int id { get; set; }
        public string MachineNumber { get; set; }
        public string CustomerName { get; set; }
        public string Purpose { get; set; }
        public string ClusterLocation { get; set; }
        public string CNG { get; set; }
        public string Mileage { get; set; }
        public string EstInterDistance { get; set; }
        public string EstCompanyDistance { get; set; }
        public string ActualODOReading { get; set; }
        public string EstTravelTime { get; set; }
        public string EstTimeForJob { get; set; }
        public string SchdETD { get; set; }
        public string ActualTime { get; set; }
        public string CNGFilledPreviously { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string TripId { get; set; }
        public Nullable<int> TravelId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
